blueprint:
  domain: automation
  source_url: https://github.com/CraigGardener/home-assistant-blueprints/blob/main/ikea-rodret.yaml
  name: IKEA RODRET
  description: "
    # IKEA RODRET

    Zigbee2MQTT blueprint for the IKEA RODRET remote.

    Works with:
    + IKEA RODRET wireless dimmer/power switch (E2201)

    Sotware Requirements:
    + ([MQTT](https://www.home-assistant.io/integrations/mqtt)
    + [Z2M addon](https://www.zigbee2mqtt.io/guide/installation/03_ha_addon.html)).

    ## Available controls:

    - Press the **on* or **off** buttons.
    - Press and hold the **on* or **off** button. Actions will be executed every *Helper - Hold delay*, but a maximum of *Helper - Max number of loops* times.
    "
  
  input:
    device:
      name: Device
      description: Select the device to use with this automation.
      default: ""
      selector:
        device:
          filter:
            integration: mqtt
            manufacturer: IKEA
            model: RODRET wireless dimmer/power switch (E2201)
    device_name:
      name: Device Name
      description: Copy the name of the device from above.
      default: ""
    base_topic:
      name: MQTT topic
      description: The topic configured in [Z2M addon](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html).
      default: zigbee2mqtt
  
    on_press_action:
      name: On - Single press action
      description: Choose action(s) to run when **on** button is pressed.
      default: []
      selector:
        action: {}
    off_press_action:
      name: Off - Single press action
      description: Choose action(s) to run when **off** button is **pressed**.
      default: []
      selector:
        action: {}
    on_hold_action:
      name: On - Hold action
      description: Choose action(s) to run when **on** button is **pressed and held**.
      default: []
      selector:
        action: {}
    off_hold_action:
      name: Off - Hold action
      description: Choose action(s) to run when **off** button is **pressed and held**.
      default: []
      selector:
        action: {}
    
    helper_hold_delay:
      name: Helper - Hold delay
      description: Delay between the execution of the **Hold** action(s).
      default: 250
      selector:
        number:
          unit_of_measurement: milliseconds
          min: 100.0
          max: 5000.0
          step: 10.0
          mode: slider
    helper_max_loops:
      name: Helper - Max number of loops
      description: Maximum number of loops when holding down a button.
      default: 20
      selector:
        number:
          min: 1.0
          max: 1000.0
          step: 1.0
          mode: slider


mode: queued
max_exceeded: silent


trigger_variables:
  z2m_base_topic: !input base_topic
  z2m_device: !input device
  z2m_device_name: !input device_name


trigger:
  - platform: mqtt
    topic: "{{ z2m_base_topic ~ '/' ~z2m_device_name ~ '/action' }}"
    payload: "on"
    id: press-on
  - platform: mqtt
    topic: "{{ z2m_base_topic ~ '/' ~z2m_device_name ~ '/action' }}"
    payload: "off"
    id: press-off
  - platform: mqtt
    topic: "{{ z2m_base_topic ~ '/' ~z2m_device_name ~ '/action' }}"
    payload: "brightness_move_up"
    id: hold-on
  - platform: mqtt
    topic: "{{ z2m_base_topic ~ '/' ~z2m_device_name ~ '/action' }}"
    payload: "brightness_move_down"
    id: hold-off
  - platform: mqtt
    topic: "{{ z2m_base_topic ~ '/' ~z2m_device_name ~ '/action' }}"
    payload: "brightness_stop"
    id: release


action:
  - variables:
      z2m_base_topic: !input base_topic
      z2m_device: !input device
      z2m_device_name: !input device_name
  - choose:
      - conditions:
          - condition: trigger
            id:
              - press-on
        sequence: !input on_press_action
      - conditions:
          - condition: trigger
            id:
              - press-off
        sequence: !input off_press_action
      - conditions:
          - condition: trigger
            id:
              - hold-on
        sequence:
          - repeat:
              count: !input helper_max_loops
              sequence:
                - parallel:
                    - sequence: !input on_hold_action
                    - sequence:
                        - choose:
                            - conditions:
                                - condition: trigger
                                  id:
                                    - hold-on
                              sequence:
                                - wait_for_trigger:
                                    - platform: mqtt
                                      topic: "{{ z2m_base_topic ~ '/' ~ z2m_device_name ~ '/action' }}"
                                      payload: "brightness_stop"
                                  timeout:
                                    milliseconds: !input helper_hold_delay
                                  continue_on_timeout: true
                                - if:
                                    - condition: template
                                      value_template: "{{ wait.trigger.idx is defined }}"
                                  then:
                                    - stop: button released
      - conditions:
          - condition: trigger
            id:
              - hold-off
        sequence:
          - repeat:
              count: !input helper_max_loops
              sequence:
                - parallel:
                    - sequence: !input off_hold_action
                    - sequence:
                        - choose:
                            - conditions:
                                - condition: trigger
                                  id:
                                    - hold-off
                              sequence:
                                - wait_for_trigger:
                                    - platform: mqtt
                                      topic: "{{ z2m_base_topic ~ '/' ~ z2m_device_name ~ '/action' }}"
                                      payload: "brightness_stop"
                                  timeout:
                                    milliseconds: !input helper_hold_delay
                                  continue_on_timeout: true
                                - if:
                                    - condition: template
                                      value_template: "{{ wait.trigger.idx is defined }}"
                                  then:
                                    - stop: button released


